name: VMSS Cap
description: Retrieve VMSS autoscale maximum capacity
inputs:
  resource_group_name:
    required: true
  autoscale_setting_name:
    required: true
outputs:
  max:
    value: ${{ steps.get.outputs.max }}
runs:
  using: composite
  steps:
    - id: get
      shell: bash
      env:
        RG: ${{ inputs.resource_group_name }}
        AS: ${{ inputs.autoscale_setting_name }}
      run: |
        MAX=$(az monitor autoscale show -g "$RG" -n "$AS" --query "profiles[0].capacity.maximum" -o tsv)
        echo "max=$MAX" >> "$GITHUB_OUTPUT"
